<?php

/**
 * PlugintdGuestbook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tdGuestbookPlugin
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PlugintdGuestbook extends BasetdGuestbook
{
  /**
   * Returns short text of the guestbook entry.
   *
   * @return String - short text.
   */
  public function getTextShort()
  {
    return tdTools::getMbShortenedString($this->getText(), sfConfig::get('td_guestbook_short_text_sign_count'));
  }

  /**
   * Activates the guestbook entry.
   *
   * @return True
   */
  public function activate()
  {
    $this->setActive(true);
    $this->save();
    return true;
  }

  /**
   * Deactivates the guestbook entry.
   *
   * @return True
   */
  public function deactivate()
  {
    $this->setActive(false);
    $this->save();
    return true;
  }
}