generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tdGuestbook
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          td_guestbook
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing
    i18n_catalogue:        sf_admin

    config:
      actions: ~
      fields:
        author:
          label: Autor
        text:
          label: Treść
        email:
          label: Adres E-mail
        http:
          label: Adres WWW
        active:
          label: Aktywny
          help: if the link shall be visible on the frontend website
        created_at:
          label: Utworzono
        updated_at:
          label: Zmieniono
      list:
        title: Guestbook entry list
        batch_actions:
          _delete: ~
          activate: ~
          deactivate: ~
        object_actions:
          _edit: ~
          _delete: ~
          activate: ~
          deactivate: ~
        display: [ active, author, text, updated_at ]
        max_per_page: 10
        layout: stacked
        params: |
          <strong>Autor</strong>: <i>%%author%%</i> %%active%%
          <br />
          <strong>Treść</strong>: <div class="text_box">%%text_short%%</div>
          <br />
          <strong>Utworzono</strong>: <i>%%created_at%%</i>
          <br />
          <strong>Zmieniono</strong>: <i>%%updated_at%%</i>
      filter:  ~
      form:
        fields:
          author:
            attributes: { size: 80 }
          email:
            attributes: { size: 80 }
          http:
            attributes: { size: 80 }
          text:
            attributes: { cols: 80, rows: 10 }
      edit:
        title: Edit guestbook entry
      new:
        title: New guestbook entry
